/**
 * Prompter API Client
 *
 * Handles streaming chat requests and conversation management.
 * Uses fetch + ReadableStream for SSE to allow POST requests with a body.
 */

import { API_URL, CEO_AGENT_ID, CEO_ROLE } from "@/lib/constants";
import { isMockMode } from "@/lib/mock-data";
import type { DraftFieldKey } from "@/store/prompter-store";
import { Team, TaskType, Complexity, TaskNature } from "@/types";

// =============================================================================
// Types
// =============================================================================

export interface PrompterStreamEvent {
  type: "token" | "draft_update" | "done" | "error";
  /** Present for type=token */
  content?: string;
  /** Present for type=draft_update */
  field?: DraftFieldKey;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  value?: any;
  /** Present for type=error */
  message?: string;
}

export interface StreamChatRequest {
  message: string;
  model: string;
  conversationId: string;
  history: Array<{ role: "user" | "assistant"; content: string }>;
}

// =============================================================================
// Mock Stream Generator
// =============================================================================

/** Simulates SSE events for mock/offline mode */
async function* mockStreamChat(
  request: StreamChatRequest
): AsyncGenerator<PrompterStreamEvent> {
  const msg = request.message.toLowerCase();

  // Generate a plausible response based on input
  const response =
    `I've analyzed your request and drafted a task for "${request.message}". ` +
    `The draft has been populated with suggested values — feel free to adjust any fields before launching.`;

  // Stream token by token (simulate realistic token cadence)
  const words = response.split(" ");
  for (const word of words) {
    await new Promise((r) => setTimeout(r, 40));
    yield { type: "token", content: word + " " };
  }

  // Send draft_update events
  await new Promise((r) => setTimeout(r, 100));
  yield {
    type: "draft_update",
    field: "title",
    value: msg.slice(0, 80) || "New task",
  };

  await new Promise((r) => setTimeout(r, 80));
  yield {
    type: "draft_update",
    field: "description",
    value: `Implement: ${request.message}. This task was generated by the Prompter AI assistant.`,
  };

  await new Promise((r) => setTimeout(r, 80));
  yield {
    type: "draft_update",
    field: "team",
    value: Team.FRONTEND,
  };

  await new Promise((r) => setTimeout(r, 80));
  yield {
    type: "draft_update",
    field: "acceptance_criteria",
    value: [
      `The feature described in the prompt is fully implemented`,
      `All edge cases are handled with appropriate error messages`,
      `Tests pass and coverage is ≥80%`,
    ],
  };

  await new Promise((r) => setTimeout(r, 80));
  yield {
    type: "draft_update",
    field: "estimated_complexity",
    value: Complexity.MEDIUM,
  };

  await new Promise((r) => setTimeout(r, 80));
  yield {
    type: "draft_update",
    field: "nature",
    value: TaskNature.TECHNICAL,
  };

  await new Promise((r) => setTimeout(r, 80));
  yield {
    type: "draft_update",
    field: "task_type",
    value: TaskType.CODE,
  };

  yield { type: "done" };
}

// =============================================================================
// SSE Stream Parser
// =============================================================================

/** Parse a raw SSE line into a PrompterStreamEvent */
function parseSseLine(line: string): PrompterStreamEvent | null {
  if (!line.startsWith("data: ")) return null;
  const raw = line.slice("data: ".length).trim();
  if (raw === "[DONE]") return { type: "done" };
  try {
    return JSON.parse(raw) as PrompterStreamEvent;
  } catch {
    return null;
  }
}

// =============================================================================
// API Implementation
// =============================================================================

export const prompterApi = {
  /**
   * Stream a chat response. Yields PrompterStreamEvent objects as they arrive.
   * Callers should iterate with `for await (const event of streamChat(...))`.
   */
  async *streamChat(
    request: StreamChatRequest
  ): AsyncGenerator<PrompterStreamEvent> {
    if (isMockMode()) {
      yield* mockStreamChat(request);
      return;
    }

    const response = await fetch(`${API_URL}/prompter/stream`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Agent-ID": CEO_AGENT_ID,
        "X-Agent-Role": CEO_ROLE,
      },
      body: JSON.stringify({
        message: request.message,
        model: request.model,
        conversation_id: request.conversationId,
        history: request.history,
      }),
    });

    if (!response.ok || !response.body) {
      yield {
        type: "error",
        message: `HTTP ${response.status}: ${response.statusText}`,
      };
      return;
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";

    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });

        // SSE events are separated by double newlines; process complete lines
        const lines = buffer.split("\n");
        // The last element may be incomplete — keep it in the buffer
        buffer = lines.pop() ?? "";

        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed) continue;
          const event = parseSseLine(trimmed);
          if (event) yield event;
        }
      }
    } finally {
      reader.releaseLock();
    }
  },
};
