"""Structural type for the composed AgentOrchestrator, TYPE_CHECKING-only.

Every ``roboco/runtime/engines/*.py`` mixin holds methods moved verbatim
out of ``AgentOrchestrator`` (see ``decomp/extract.py``); many reference
attributes and methods that live on a DIFFERENT mixin, or on the core class
itself (declared in ``__init__`` / at class scope). mypy checks each mixin
file against its own declared bases only, so it does not know ``self`` is
ultimately a full ``AgentOrchestrator`` with every sibling mixin composed in.

This Protocol names that full cross-mixin surface (mechanically generated
from mypy's own ``has no attribute`` findings against the fresh split, one
entry per distinct missing name, its real return type -- and staticmethod/
classmethod decorator, where the real definition has one, since the
`AgentOrchestrator.foo(...)` class-qualified call pattern some moved bodies
use needs it -- copied from wherever it is actually defined; an
``*args``/``**kwargs`` stub, not the real parameter list, since only a
call's RETURN type needs to be right here, the real signature stays
enforced by the file that actually defines each one). Each mixin's own
module gives its class a TYPE_CHECKING-only base of this Protocol (see any
mixin's own ``if TYPE_CHECKING:`` block) so every method's implicit ``self``
resolves the whole surface, with ZERO changes to any moved method body.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar, Protocol

if TYPE_CHECKING:
    import asyncio
    from datetime import datetime, timedelta
    from pathlib import Path
    from uuid import UUID

    from roboco.llm.providers import ProviderRegistry
    from roboco.models.runtime import AgentInstance, SpawnGitContext, WaitingRecord
    from roboco.models.sandbox import SandboxInfo
    from roboco.runtime.sandbox import SandboxProvisioner
    from roboco.services.llm import AgentRoute
    from roboco.services.uptime import UptimeLedger


class AgentOrchestratorSelf(Protocol):
    """Every cross-mixin attribute/method a moved method body reaches via ``self``."""

    UPTIME_LOOKBACK_DAYS: int
    UPTIME_REFRESH_SECONDS: int
    _AUTO_SUBMIT_VERB_BY_ROLE: ClassVar[dict[str, tuple[str, str]]]
    _BOARD_AGENTS: ClassVar[frozenset[str]]
    _BOARD_KEYWORDS: frozenset[str]
    _CROSS_CELL_KEYWORDS: frozenset[str]
    _DISPATCH_HEARTBEAT_SECONDS: int
    _GATE_CI_STATUS_CACHE_TTL_SECONDS: ClassVar[float]
    _MIN_DESCRIPTION_LEN: int
    _NOTIFICATION_COOLDOWN_PRUNE_AT: int
    _PM_AGENTS: ClassVar[frozenset[str]]
    _PM_KEYWORDS: frozenset[str]
    _PM_RESPAWN_MAX_REVISIT_RESETS: int
    _PM_RESPAWN_MAX_TRACING_RESETS: int
    _PM_RESPAWN_MAX_UNPRODUCTIVE: int
    _PM_RESPAWN_TRIP_COOLDOWN_SECONDS: int
    _ROLE_BUILTIN_TOOLS: ClassVar[dict[str, tuple[str, ...]]]
    _TEAM_PM_MAP: ClassVar[dict[str, str]]
    _TEAM_ROUTING_MAP: ClassVar[dict[str, str]]
    _TOOL_LOAD_CACHE: ClassVar[dict[str, str]]
    _auth_ceo_notified: set[str]
    _auth_parked_agents: set[str]
    _bg_tasks: set[asyncio.Task[None]]
    _board_dispatched: set[tuple[str, str]]
    _board_review_ceo_notified: set[str]
    _claim_heartbeat_ttl: int
    _closure_recently_paused_ttl: int
    _dispatch_wake: asyncio.Event
    _gate_ci_status_cache: dict[tuple[str, int], tuple[float, str | None]]
    _gateway_broken_since: dict[str, datetime]
    _gemini_last_park_at: datetime | None
    _gemini_repark_count: int
    _grok_last_park_at: datetime | None
    _grok_repark_count: int
    _instances: dict[str, AgentInstance]
    _intake_spawn_lock: asyncio.Lock
    _last_audit_spawn_at: datetime | None
    _last_image_prune: datetime | None
    _last_transcript_prune: datetime | None
    _lock: asyncio.Lock
    _loop_heartbeats: dict[str, tuple[float, float]]
    _notification_spawn_at: dict[tuple[str, str], float]
    _notification_spawn_count: dict[tuple[str, str], int]
    _pm_respawn_tracker: dict[tuple[str, str], dict[str, Any]]
    _provider_registry: ProviderRegistry | None
    _rate_limit_ceo_notified: set[str]
    _respawn_persist_lock: asyncio.Lock
    _resume_confirm_delay: float
    _running: bool
    _sandbox: SandboxProvisioner
    _sandbox_info: dict[str, SandboxInfo]
    _secretary_spawn_lock: asyncio.Lock
    _supersede_cuts_in_flight: set[str]
    _supersede_lock: asyncio.Lock
    _tick_handled_tasks: set[str]
    _uptime: UptimeLedger | None
    _uptime_loaded_at: datetime | None
    _waiting_records: dict[str, WaitingRecord]
    dispatcher_interval: int
    project_root: Path

    async def _ack_alert_as_auditor(self, *args: Any, **kwargs: Any) -> None: ...
    def _active_age(self, *args: Any, **kwargs: Any) -> timedelta: ...
    @staticmethod
    def _all_descendants_terminal(*args: Any, **kwargs: Any) -> bool: ...
    @staticmethod
    def _already_promoted_for_closure(*args: Any, **kwargs: Any) -> bool: ...

    @property
    def _api_url(self) -> str: ...

    def _audit_spawn_cooled(self, *args: Any, **kwargs: Any) -> bool: ...
    async def _auto_block_task(self, *args: Any, **kwargs: Any) -> None: ...
    async def _blocked_by_earlier_lane_sibling(
        self, *args: Any, **kwargs: Any
    ) -> bool: ...
    async def _blocked_by_earlier_sibling(self, *args: Any, **kwargs: Any) -> bool: ...
    def _blocker_resolver_slug(self, *args: Any, **kwargs: Any) -> str | None: ...
    def _build_a2a_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_approval_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_audit_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_barfly_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_board_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_coroner_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    async def _build_dev_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_doc_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_dogfood_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_escalation_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_feature_spotlight_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_librarian_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_main_pm_triage_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_marketing_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_megaphone_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_mirror_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_periscope_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_pest_control_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_pm_blocker_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_pm_closure_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_pm_review_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_pm_triage_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_pr_gate_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_pr_review_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_qa_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_roadmap_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_scales_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_sentinel_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_spackle_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_vault_curation_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    def _build_war_room_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    async def _check_dependencies_terminal(
        self, *args: Any, **kwargs: Any
    ) -> str | None: ...
    async def _claim_and_spawn_guarded(
        self, *args: Any, **kwargs: Any
    ) -> bool | None: ...
    async def _claim_and_spawn_routed_agent(
        self, *args: Any, **kwargs: Any
    ) -> None: ...
    def _claimed_task_needs_agent(self, *args: Any, **kwargs: Any) -> str | None: ...
    def _claude_session_id_for(self, *args: Any, **kwargs: Any) -> str | None: ...
    async def _closure_handled_without_pm(
        self, *args: Any, **kwargs: Any
    ) -> tuple[bool, str | None]: ...
    def _closure_pm_for_team(self, *args: Any, **kwargs: Any) -> str: ...
    def _codex_usage_tokens(
        self, *args: Any, **kwargs: Any
    ) -> tuple[int, int, int, int]: ...
    async def _cut_supersede_branch(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def _default_spawn_prompt(*args: Any, **kwargs: Any) -> str: ...
    @staticmethod
    def _description_body(*args: Any, **kwargs: Any) -> str: ...
    async def _detect_stuck_tasks(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def _dev_dispatch_role_matches(*args: Any, **kwargs: Any) -> bool: ...
    async def _dispatch_all_work(self, *args: Any, **kwargs: Any) -> None: ...
    async def _emit_dispatcher_heartbeat(self, *args: Any, **kwargs: Any) -> None: ...
    async def _enforce_grok_cost_budget(self, *args: Any, **kwargs: Any) -> None: ...
    async def _ensure_agent_image(self, *args: Any, **kwargs: Any) -> None: ...
    def _ensure_codex_usage_dir(self, *args: Any, **kwargs: Any) -> None: ...
    def _ensure_gemini_usage_dir(self, *args: Any, **kwargs: Any) -> None: ...
    def _ensure_grok_usage_dir(self, *args: Any, **kwargs: Any) -> None: ...
    async def _ensure_image_present(self, *args: Any, **kwargs: Any) -> None: ...
    def _ensure_kimi_usage_dir(self, *args: Any, **kwargs: Any) -> None: ...
    async def _ensure_review_pm_assigned(
        self, *args: Any, **kwargs: Any
    ) -> str | None: ...
    async def _fetch_all_descendants(
        self, *args: Any, **kwargs: Any
    ) -> list[dict[str, Any]]: ...
    async def _fetch_notifications(
        self, *args: Any, **kwargs: Any
    ) -> list[dict[str, Any]]: ...
    async def _fetch_task_fields(
        self, *args: Any, **kwargs: Any
    ) -> dict[str, Any] | None: ...
    async def _fetch_tasks(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...
    async def _finalize_spawn_session(self, *args: Any, **kwargs: Any) -> None: ...
    def _fire_audit(self, *args: Any, **kwargs: Any) -> None: ...
    async def _gate_task_ci_pending(self, *args: Any, **kwargs: Any) -> bool: ...
    def _gate_task_reviewer(self, *args: Any, **kwargs: Any) -> str | None: ...
    def _gemini_usage_json(
        self, *args: Any, **kwargs: Any
    ) -> dict[str, Any] | None: ...
    def _gemini_usage_tokens(
        self, *args: Any, **kwargs: Any
    ) -> tuple[int, int, int, int]: ...
    def _generate_agent_settings(self, *args: Any, **kwargs: Any) -> Path: ...
    def _generate_composed_prompt(self, *args: Any, **kwargs: Any) -> Path: ...
    async def _generate_mcp_config(self, *args: Any, **kwargs: Any) -> Path: ...
    async def _get_prompt_for_agent(self, *args: Any, **kwargs: Any) -> str: ...
    def _get_task_age(self, *args: Any, **kwargs: Any) -> timedelta | None: ...
    def _grok_usage_json(self, *args: Any, **kwargs: Any) -> dict[str, Any] | None: ...
    def _grok_usage_tokens(
        self, *args: Any, **kwargs: Any
    ) -> tuple[int, int, int, int]: ...
    async def _handle_board_assigned_task(self, *args: Any, **kwargs: Any) -> None: ...
    async def _handle_dev_existing_owner(self, *args: Any, **kwargs: Any) -> None: ...
    async def _handle_stopped_container(self, *args: Any, **kwargs: Any) -> None: ...
    async def _has_recent_delivery_activity(
        self, *args: Any, **kwargs: Any
    ) -> bool: ...
    @staticmethod
    async def _inspect_container_state(
        *args: Any, **kwargs: Any
    ) -> tuple[bool, int | None]: ...
    def _is_agent_active(self, *args: Any, **kwargs: Any) -> bool: ...
    def _is_claim_in_flight(self, *args: Any, **kwargs: Any) -> bool: ...
    async def _is_dogfood_spawn(self, *args: Any, **kwargs: Any) -> bool: ...
    @staticmethod
    def _is_hitl_blocked(*args: Any, **kwargs: Any) -> bool: ...
    def _is_parallel_phase_claim(self, *args: Any, **kwargs: Any) -> bool: ...
    async def _is_paused(self, *args: Any, **kwargs: Any) -> bool: ...
    def _is_recently_paused(self, *args: Any, **kwargs: Any) -> bool: ...
    def _is_task_handled_this_tick(self, *args: Any, **kwargs: Any) -> bool: ...
    async def _is_video_authoring_spawn(self, *args: Any, **kwargs: Any) -> bool: ...
    def _kimi_usage_tokens(
        self, *args: Any, **kwargs: Any
    ) -> tuple[int, int, int, int]: ...
    def _make_tracker(self, *args: Any, **kwargs: Any) -> Any: ...
    def _mark_task_handled(self, *args: Any, **kwargs: Any) -> None: ...
    async def _next_unobserved_audit_alert(
        self, *args: Any, **kwargs: Any
    ) -> dict[str, Any] | None: ...
    async def _notification_has_live_work(self, *args: Any, **kwargs: Any) -> bool: ...
    async def _notification_spawn_cooled(self, *args: Any, **kwargs: Any) -> bool: ...
    async def _notify_stuck_agent(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def _parse_iso_dt(*args: Any, **kwargs: Any) -> datetime | None: ...
    @staticmethod
    def _parse_supersede_author(*args: Any, **kwargs: Any) -> str: ...
    async def _pending_claim_blocked(self, *args: Any, **kwargs: Any) -> bool: ...
    async def _pm_respawn_should_gate(self, *args: Any, **kwargs: Any) -> bool: ...
    async def _pm_spawn_prompt(self, *args: Any, **kwargs: Any) -> str: ...
    async def _probe_one_provider(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def _projects_one_per_key(cls, *args: Any, **kwargs: Any) -> list[Any]: ...
    async def _reap_stale_claims(self, *args: Any, **kwargs: Any) -> None: ...
    def _record_expected_stop(self, *args: Any, **kwargs: Any) -> None: ...
    def _record_loop_heartbeat(self, *args: Any, **kwargs: Any) -> None: ...
    async def _record_spawn_session(self, *args: Any, **kwargs: Any) -> UUID | None: ...
    async def _refresh_codex_auth(self, *args: Any, **kwargs: Any) -> None: ...
    async def _refresh_grok_auth(self, *args: Any, **kwargs: Any) -> None: ...
    async def _refresh_uptime(self, *args: Any, **kwargs: Any) -> UptimeLedger: ...
    async def _release_claim_to_pending(self, *args: Any, **kwargs: Any) -> None: ...
    async def _remove_container(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def _repo_key(*args: Any, **kwargs: Any) -> str: ...
    async def _resolve_agent_route(self, *args: Any, **kwargs: Any) -> AgentRoute: ...
    def _resolve_agent_slug(self, *args: Any, **kwargs: Any) -> str: ...
    @staticmethod
    def _resolve_cli_model(*args: Any, **kwargs: Any) -> str: ...
    async def _resolve_conventions_ambient(
        self, *args: Any, **kwargs: Any
    ) -> str | None: ...
    @staticmethod
    def _resolve_dev_owner_uuid(*args: Any, **kwargs: Any) -> str | None: ...
    async def _respawn_dev_for_pr_half(self, *args: Any, **kwargs: Any) -> None: ...
    async def _respawn_dev_if_inactive(self, *args: Any, **kwargs: Any) -> None: ...
    async def _review_pm_slug(self, *args: Any, **kwargs: Any) -> str | None: ...
    async def _route_unassigned_pm_task(self, *args: Any, **kwargs: Any) -> None: ...
    async def _sandbox_available_services(
        self, *args: Any, **kwargs: Any
    ) -> list[str]: ...
    async def _sandbox_janitor_sweep(self, *args: Any, **kwargs: Any) -> None: ...
    def _schedule_bg(self, *args: Any, **kwargs: Any) -> None: ...
    def _select_agent_for_cell(self, *args: Any, **kwargs: Any) -> str | None: ...
    async def _sweep_rate_limit_probes(self, *args: Any, **kwargs: Any) -> None: ...
    async def _sync_gate_reviewer_assignment(
        self, *args: Any, **kwargs: Any
    ) -> None: ...
    def _task_git_context(
        self, *args: Any, **kwargs: Any
    ) -> SpawnGitContext | None: ...
    async def _task_has_children(self, *args: Any, **kwargs: Any) -> bool: ...
    @staticmethod
    def _usage_from_transcript(
        *args: Any, **kwargs: Any
    ) -> tuple[int, int, int, int, int]: ...
    async def _validate_task_for_spawn(
        self, *args: Any, **kwargs: Any
    ) -> str | None: ...
    async def _write_agent_briefing(self, *args: Any, **kwargs: Any) -> Path | None: ...
    async def spawn_agent(self, *args: Any, **kwargs: Any) -> AgentInstance: ...
    async def stop_agent(self, *args: Any, **kwargs: Any) -> None: ...
